### ISSUE TITLE
Backend Task Discussion

### ISSUE THREAD

**Issue by atharva-gadekar** [GeekHaven/WebD-Selection-23-24-Final-Tasks#3]
You may post your queries here. You may seek any help related to the resources needed in this thread.

**Comment by bhupesh98** [comment]
@atharva-gadekar  Sir, is there any better and efficient way to store images than using multer to convert image to binary explicitly? Like, isn't there any built-in technique in mongoDB to store images/videos or any other file?

**Comment by GammaMicrowave** [comment]
> @atharva-gadekar  Sir, is there any better and efficient way to store images than using multer to convert image to binary explicitly? Like, isn't there any built-in technique in mongoDB to store images/videos or any other file?

When you send data from front-end having a file, It usually comes in a multi-part form data. Here you could not directly access that file unless and until you temporarily process it in a different format first. This is done in order to perform certain tasks like compressing or decompressing the images before uploading it to your cloud storage and since you can store this file temporarily in ram it won't effect your server in a long run. Now mongodb also have a storage for storing large files it is known as gridFS you can look into it if you want.
